apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds-amd64
  namespace: kube-system
spec:
  template:
    spec:
      tolerations:
      - operator: Exists
---
# Tweak network range to avoid using GCP auto mode VPC range.
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: kube-flannel-cfg
data:
  net-conf.json: |
    {
      "Network": "192.168.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
